-- Drop existing senior_citizens table
DROP TABLE IF EXISTS senior_citizens CASCADE;

-- Create senior_citizens table with correct schema
CREATE TABLE senior_citizens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  osca_id VARCHAR(50) NOT NULL UNIQUE,
  ncsc_rrn VARCHAR(50),
  last_name VARCHAR(100) NOT NULL,
  first_name VARCHAR(100) NOT NULL,
  middle_name VARCHAR(100),
  ext_name VARCHAR(20),
  full_name VARCHAR(255) GENERATED ALWAYS AS (
    last_name || ', ' || first_name || 
    CASE WHEN middle_name IS NOT NULL AND middle_name != '' THEN ' ' || middle_name ELSE '' END ||
    CASE WHEN ext_name IS NOT NULL AND ext_name != '' THEN ' ' || ext_name ELSE '' END
  ) STORED,
  date_of_birth DATE NOT NULL,
  sex VARCHAR(10) NOT NULL CHECK (sex IN ('Male', 'Female')),
  civil_status VARCHAR(20) NOT NULL CHECK (civil_status IN ('Single', 'Married', 'Widowed', 'Separated', 'Legally Separated')),
  citizenship VARCHAR(20) NOT NULL DEFAULT 'Filipino' CHECK (citizenship IN ('Filipino', 'Dual')),
  is_ip BOOLEAN DEFAULT false,
  ip_group VARCHAR(100),
  is_pwd BOOLEAN DEFAULT false,
  pwd_type VARCHAR(100),
  region VARCHAR(100) NOT NULL,
  province VARCHAR(100) NOT NULL,
  municipality VARCHAR(100) NOT NULL,
  barangay VARCHAR(100) NOT NULL,
  house_number VARCHAR(50),
  street VARCHAR(100),
  full_address TEXT GENERATED ALWAYS AS (
    CASE WHEN house_number IS NOT NULL AND house_number != '' THEN house_number || ' ' ELSE '' END ||
    CASE WHEN street IS NOT NULL AND street != '' THEN street || ', ' ELSE '' END ||
    barangay || ', ' || municipality || ', ' || province || ', ' || region
  ) STORED,
  spouse_name VARCHAR(255),
  rep_1_name VARCHAR(255),
  rep_1_relationship VARCHAR(100),
  rep_2_name VARCHAR(255),
  rep_2_relationship VARCHAR(100),
  rep_3_name VARCHAR(255),
  rep_3_relationship VARCHAR(100),
  beneficiary_primary VARCHAR(255),
  beneficiary_contingent VARCHAR(255),
  status VARCHAR(50) DEFAULT 'DRAFT' CHECK (status IN ('DRAFT', 'PENDING_ADMIN_REVIEW', 'CLEAN', 'DUPLICATE', 'SUSPECTED', 'APPROVED', 'HOLD', 'DENIED', 'SYNCED')),
  compliance_check VARCHAR(10) CHECK (compliance_check IN ('PASS', 'FAIL')),
  global_duplicate_status VARCHAR(20) CHECK (global_duplicate_status IN ('CLEAN', 'DUPLICATE', 'SUSPECTED')),
  admin_assessment VARCHAR(20) CHECK (admin_assessment IN ('APPROVED', 'HOLD', 'DENIED')),
  admin_remarks TEXT,
  payment_status VARCHAR(20) DEFAULT 'UNPAID' CHECK (payment_status IN ('UNPAID', 'PAID')),
  payment_date DATE,
  date_of_death DATE,
  lgu_id INTEGER NOT NULL,
  locked BOOLEAN DEFAULT false,
  synced_to_supabase BOOLEAN DEFAULT false,
  submitted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create indexes
CREATE INDEX idx_senior_citizens_osca_id ON senior_citizens(osca_id);
CREATE INDEX idx_senior_citizens_full_name_dob ON senior_citizens(full_name, date_of_birth);
CREATE INDEX idx_senior_citizens_lgu_id ON senior_citizens(lgu_id);
CREATE INDEX idx_senior_citizens_status ON senior_citizens(status);
CREATE INDEX idx_senior_citizens_global_duplicate ON senior_citizens(global_duplicate_status);

-- Create trigger for updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_senior_citizens_updated_at 
    BEFORE UPDATE ON senior_citizens 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

-- NOTE: RLS is disabled for testing
-- To enable RLS later, you'll need to properly configure session variables
-- or use Supabase Auth with JWT claims

-- Grant permissions
GRANT ALL ON senior_citizens TO authenticated;
GRANT SELECT ON senior_citizens TO anon;
